title: Crown Creatives
description: Artistry • Resilience • Imagination
baseurl: ""
url: "https://crowncreatives.github.io"

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-seo-tag
