backend:
  name: github
  repo: CrownCreatives/crowncreatives.github.io
  branch: main
  auth_scope: repo
  client_id: Ov2311MG2inEpdlRIr1M9

media_folder: "assets/images"
public_folder: "/assets/images"

site_url: "https://crowncreatives.github.io"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
